# AlexNet 模型配置文件

# 模型参数
model:
  name: "AlexNet"
  num_classes: 1000  # 分类类别数 (ImageNet: 1000, CIFAR-10: 10, CIFAR-100: 100)
  input_channels: 3  # 输入通道数 (RGB图: 3)
  dropout: 0.5  # Dropout比例
  use_lrn: true  # 是否使用局部响应归一化 (原始AlexNet特性)

# 训练参数
training:
  batch_size: 128
  epochs: 90
  learning_rate: 0.01
  weight_decay: 5e-4
  momentum: 0.9
  
  # 学习率调度
  scheduler:
    type: "StepLR"  # StepLR, CosineAnnealingLR, ReduceLROnPlateau
    step_size: 30
    gamma: 0.1
  
  # 优化器
  optimizer:
    type: "SGD"  # SGD, Adam, AdamW
    momentum: 0.9

# 数据参数
data:
  dataset: "ImageNet"  # ImageNet, CIFAR10, CIFAR100
  data_root: "./data"
  num_workers: 8
  pin_memory: true
  
  # 数据增强
  augmentation:
    enabled: true
    resize: 256  # 重新调整尺寸
    crop_size: 224  # 中心裁剪尺寸
    horizontal_flip: true
    color_jitter:
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
      hue: 0.1
    normalize:
      mean: [0.485, 0.456, 0.406]  # ImageNet归一化参数
      std: [0.229, 0.224, 0.225]

# 验证参数
validation:
  val_split: 0.1  # 验证集比例
  eval_frequency: 1  # 每隔多少个epoch验证一次

# 保存参数
save:
  checkpoint_dir: "./checkpoints/alexnet"
  save_frequency: 10  # 每隔多少个epoch保存一次
  save_best_only: true  # 是否只保存最佳模型

# 日志参数
logging:
  log_dir: "./logs/alexnet"
  tensorboard: true
  print_frequency: 100  # 每隔多少个batch打印一次

# 硬件参数
device:
  use_cuda: true
  device_ids: [0, 1]  # 多GPU训练
  mixed_precision: true  # 混合精度训练