# BERT Configuration
model_name: "bert"
vocab_size: 30522
hidden_size: 768
num_hidden_layers: 12
num_attention_heads: 12
intermediate_size: 3072
max_position_embeddings: 512
type_vocab_size: 2
attention_probs_dropout_prob: 0.1
hidden_dropout_prob: 0.1
layer_norm_eps: 1e-12

# Task-specific configuration
task_type: "masked_lm"  # Options: "masked_lm", "sequence_classification"
num_labels: 2  # Only for sequence classification

# Training configuration
batch_size: 32
learning_rate: 5e-5
weight_decay: 0.01
warmup_steps: 10000
max_steps: 1000000
optimizer: "adamw"

# Data configuration
dataset: "bookcorpus_wiki"
data_path: "/path/to/dataset"
max_seq_length: 512
mlm_probability: 0.15
num_workers: 4