# MAE Configuration
model_name: "mae"
img_size: 224
patch_size: 16
in_chans: 3
embed_dim: 768
encoder_depth: 12
encoder_num_heads: 12
decoder_embed_dim: 512
decoder_depth: 8
decoder_num_heads: 16
mlp_ratio: 4.0
mask_ratio: 0.75
norm_pix_loss: true

# Training configuration
batch_size: 64
learning_rate: 1.5e-4
weight_decay: 0.05
warmup_epochs: 40
max_epochs: 800
optimizer: "adamw"

# Data configuration
dataset: "imagenet"
data_path: "/path/to/imagenet"
num_workers: 8