# Swin Transformer Configuration
model_name: "swin_transformer"
img_size: 224
patch_size: 4
in_chans: 3
num_classes: 1000
embed_dim: 96
depths: [2, 2, 6, 2]
num_heads: [3, 6, 12, 24]
window_size: 7
mlp_ratio: 4.0
qkv_bias: true
qk_scale: null
drop_rate: 0.0
attn_drop_rate: 0.0
drop_path_rate: 0.1
ape: false
patch_norm: true

# Training configuration
batch_size: 128
learning_rate: 5e-4
weight_decay: 0.05
warmup_epochs: 20
max_epochs: 300
optimizer: "adamw"

# Data configuration
dataset: "imagenet"
data_path: "/path/to/imagenet"
num_workers: 8
mixup_alpha: 0.8
cutmix_alpha: 1.0
label_smoothing: 0.1